defaults:
  - _self_
  - judger: judger
  - solver: solver

evaluation:
  mode: "all" # options: "all", "solver_only", "judger_only"

paths:
  data_dir: "data"
  save_dir: "outputs"

data:
  problem_file: "problems.csv"
  solver_output_file: None

outputs:
  experiment_id: "base"
  save_solver_outputs: true

template:
  solver_templates: ["base_solver"]
  judger_templates: ["base_judger"]
  extract_field_func_for_solver: "nothing"
  extract_field_func_for_judger: "nothing"
  use_images_for_judger: True
