defaults:
  - _self_
  - judger: judger
  - solver: solver

paths:
  data_dir: ""
  save_dir: "../outputs"
  templates_dir: ""

data:
  problems_files: ["problems.csv"]

outputs:
  experiment_id: "base"
  save_solver_outputs: true
  save_judger_inputs: true
  save_judger_results: true

template:
  solver_template: "base_solver.jinja"
  judger_template: "base_judger.jinja"
  use_extract_answer: true
  extract_answer_func: "boxed_answer_extractor"